# Generated by Django 4.1.3 on 2022-12-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('rasm_url', models.CharField(max_length=255)),
                ('tarif', models.TextField()),
            ],
        ),
    ]
